In [1]:
import numpy as np
from numpy import linalg
import time

matriz_p = np.array([[.3, .2, .5],[.2, .3, .5],[.25, .25, .5]])



# (matriz_p)^2
print("multiplicação comum:\n")
start = time.time()
print(np.matmul(matriz_p,matriz_p))
end = start - time.time()
print(f"tempo de execução:{end} segundos")

multiplicação comum:

[[0.255 0.245 0.5  ]
 [0.245 0.255 0.5  ]
 [0.25  0.25  0.5  ]]
tempo de execução:-0.0020177364349365234 segundos


In [12]:
# (matriz_p)^100
potencia = np.power(10, 1000)

'''
print("multiplicação comum:\n")
start = time.time()
matriz = matriz_p
for _ in range(potencia-1):
    matriz=np.matmul(matriz_p, matriz)

print(matriz)
end = start - time.time()
print(f"tempo de execução:{end} segundos")
'''


P = linalg.eig(matriz_p)[1]
D = np.diag(linalg.eig(matriz_p)[0])
P_inversa = linalg.inv(P)

start = time.time()
A_2 = np.matmul(np.matmul(P, np.power(D, potencia)), P_inversa)
print("\n decomposição espectral:\n")
print(A_2)
end = start - time.time()
print(f"tempo de execução:{end} segundos")


 decomposição espectral:

[[ 0.5        -0.5         1.22474487]
 [-0.5         0.5        -1.22474487]
 [ 0.81649658 -0.81649658  2.        ]]
tempo de execução:-0.0010039806365966797 segundos


### Questão 2 da VAE 1

In [4]:
import numpy as np
from numpy import linalg
matriz_p = np.array([[.5, 0, .5],[0, 1, 0],[.5, 0, .5]])

In [11]:
np.set_printoptions(suppress=True)
P = linalg.eig(matriz_p)[1]
D = np.diag(linalg.eig(matriz_p)[0])
P_inversa = linalg.inv(P)

In [12]:
P

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [13]:
D

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [16]:
P_inversa

array([[ 0.70710678,  0.        ,  0.70710678],
       [-0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  1.        ,  0.        ]])

In [17]:
potencia = 4
np.matmul(np.matmul(P, np.power(D, potencia)), P_inversa)

array([[0.5, 0. , 0.5],
       [0. , 1. , 0. ],
       [0.5, 0. , 0.5]])